bluerov_interface:
  udp_mavlink: 'udpin:192.168.2.1:14550'
  num_thrusters: 8
  depth_atm_pressure: 10.1452685894133 # 1.028*10.19977334
  watchdog_thrusters: 1.0  # Time the motors can wait without receiving data from inner-loops (otherwise they time-out and stop)
  safety_thrusters: 1.0    # Time until we recognize we have disconnected from the safety
  battery_offset: 1.16 # V
  battery_gain: 1.0

dvl_interface:
  ip: "192.168.2.95"
  port: 16171

ahrs_interface:
  port: "/dev/ttyVUSB1"
  baudrate: 115200
  use_position: false
  frame_id: ahrs2

  config_commands: [
  "VNWRG,06,0", # Stop Asynch 
  "VNRFS", #  Restore factory resets  
  "VNWRG,06,0", #  Stop Asynch (default msg is YMR reg6_14, 40 Hz)  
  "VNWRG,35,0,0,0,0", #  VPE Disabled  
  "VNWRG,36,5,5,5,0,0,0,0,0,0", #  trust (5) in mags and no adaptive tuning or filtering (IF VPE Off, is irrelevant.)  
  "VNWRG,44,0,1,5", #  Turn OFF real-time mag calibration algorithm and output compensation)  
  "VNWRG,26,1,0,0,0,1,0,0,0,1", #  Reference Frame (Sensor to Body)  
  "VNWRG,83,1,1,0,0,1000,2016.1,+43.933115,+15.444187,+100.000", #  Use Mag and Grav Models for Lisbon  
  "VNWRG,23,2.3057,-0.0203,0,-0.0203,2.5424,0,0,0,2.2909,0.0639,0.0173,0",
  "VNWNV", #  Write settings to  memory  
  "VNRST", #  Reset the Kalman Filter  
  ]

  check_commands: [
  "VNWRG,07,10", #  Asynch data output rate 10 [Hz]  
  "VNWRG,06,14", #  (reg6_14) YMR, Magnet, Accel [m/s^2], Gyros [rad/s]  
  "VNRRG,21", #  Read Mag and Grav model vectors  
  "VNRRG,23", #  Read Calibration mode  
  "VNRRG,26", #  Install matrix  
  "VNRRG,35", #  VPE Basic Control  
  "VNRRG,36", #  Basic Magnetometers Configuration  
  "VNRRG,37", #  Advanced Magnetometers Configuration  
  "VNRRG,83", #  Read Mag and Grav model cfg and position/date  
  ]